#cloud-config

timezone: Europe/Paris

hostname: ${hostname}
fdqn: ${hostname}.localdomain
prefer_fqdn_over_hostname: false
create_hostname_file: true

ssh_pwauth: false
disable_root: true
allow_public_ssh_keys: true

users:
  - name: user01
    shell: /bin/bash
    sudo: ALL=(ALL) ALL
    groups: wheel
    lock_passwd: true
    ssh_authorized_keys:
      - ${ssh_public_key}

chpasswd:
  expire: false
  users:
    - name: user01
      password: ${hashed_passwd}

# Default: false
package_update: true

packages:
  - qemu-guest-agent
  - python3-libdnf5
  - vim
  - firewalld

yum_repos:
  kubernetes:
    name: Kubernetes
    baseurl: https://pkgs.k8s.io/core:/stable:/v1.33/rpm/
    gpgcheck: true
    gpgkey: https://pkgs.k8s.io/core:/stable:/v1.33/rpm/repodata/repomd.xml.key
    enabled: true
yum_repo_dir: /etc/yum.repos.d/

# test of writing content
write_files:
  - content: |
      The quick brown fox jumped
      over the lazy dog
    path: /root/test.txt

bootcmd:
  - [sh, -c, "echo $(date) | sudo tee -a /root/bootcmd.log"]
# run once for setup

runcmd:
  - sudo systemctl daemon-reload
  - sudo systemctl enable qemu-guest-agent.service
  - sudo systemctl start qemu-guest-agent.service
  - localectl set-keymap fr
  - localectl set-locale LANG=fr_FR.UTF8
# written to /var/log/cloud-init-output.log
final_message: "The system is finally up, after $UPTIME seconds"
